# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d0e9400c1dbd7af0da59b97e55aa1f9a45f33e2315271a3b21438b04d051e7d90e8f2b5a01e636282a2170d809cf652423dd576869a21f8579c7571be1486c4

test:
  secret_key_base: 6c4244f74ac6a61505c9e28b65ae24b36f4e0462a8a69a2cc3dcc0f7952f09d5a16bb366f485a2bb4a09c4be7b044f0885df257ec815e57ca7d86a925b7ab153

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
